### ISSUE TITLE
Set up to-do list and assign tasks

### ISSUE THREAD

**Issue by Kriesse** [cssconf/CSSclasses--old#79]
Not code-related, but tracking this here for convenience. 
@bastianalbers @verpixelt @autofocus CC'ing you, please add if I forgot anything :)
- [x] set up tables and chairs (min 4 ppl)
- [x] start projector and presentation (1)
- [x] set up name tags and pens (1)
- [x] make coffee (1)
- [x] set up snacks and drinks (1)
- [x] lead Coaches Briefing (1)
- [x] watch Twitter / Slack / meetup.com and reply to last minute questions for ppl who get lost etc. (1)
- [x] welcome attendees and make sure no one stands around confusedly (1, everyone)
- [x] have a gate / elevator key ready for ppl who need assistance 
- [x] start to seat learners, help them with wi fi and installing an editor [everyone]
- [x] print feedback questionnaire

**Comment by Lucie-H** [comment]
I would add: Print feedback questionnaire.

**Comment by lukaszklis** [comment]
Have you thought about getting some spare extension cords?

**Comment by Kriesse** [comment]
@lukaszklis Good point – I think coup should have enough. If the ones on the 3rd floor aren't sufficient we can grab some more from the 5th floor :)
